basePath: /api/v1
info:
  contact:
    email: correomandos@zeke.cl
    name: Zeke
    url: http://www.zeke.cl
  description: Ejemplo uso Chi Go para pruebas de concepto
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Ejemplo Web 001
  version: "1.0"
paths: {}
swagger: "2.0"
